# Generated by Django 5.0.6 on 2024-06-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='archivo',
            new_name='file',
        ),
    ]
