# Generated by Django 5.0.6 on 2024-06-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=1, upload_to='archivos_pdf/'),
            preserve_default=False,
        ),
    ]
