# Generated by Django 5.0.6 on 2024-06-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank='', default='', upload_to='archivos_pdf/'),
        ),
    ]
